### ISSUE TITLE
Enable typescript strict mode

### ISSUE THREAD

**Issue by scottanderson** [openfrontio/OpenFrontIO#1075]
- Enable strict mode in `tsconfig.json`. See https://www.typescriptlang.org/tsconfig/#strict
- Work through compile errors, fixing each issue as appropriate.
- It may be necessary to break this change up in to multiple PRs, changing a small amount of files at one time before finally enabling the tsconfig.json rule.

**Comment by antoine-gannat** [comment]
Started working on this.

**Comment by drillskibo** [comment]
#1628 broke the deployment, it got reverted in #1713 
Reopening this issue since it still needs to be worked on.
@antoine-gannat Are you okay to take a look at it?

**Comment by aaa4xu** [comment]
The issue is on this line: https://github.com/openfrontio/OpenFrontIO/blob/63cb51a4f9216761e00ac79746a7f70b2c8d8529/Dockerfile#L49
A quick fix is to remove the `--omit=dev` argument. This makes the build succeed, but it increases the Docker image size from ~700MB to ~1GB.

Here's the log after I managed to get ts-node to stop swallowing errors:
```
src/server/Cloudflare.ts(3,18): error TS7016: Could not find a declaration file for module 'js-yaml'. '/usr/src/app/node_modules/js-yaml/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/js-yaml` if it exists or add a new declaration (.d.ts) file containing `declare module 'js-yaml';`

src/server/Master.ts(2,21): error TS7016: Could not find a declaration file for module 'express'. '/usr/src/app/node_modules/express/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
src/server/Master.ts(29,18): error TS7006: Parameter 'res' implicitly has an 'any' type.
src/server/Master.ts(29,23): error TS7006: Parameter 'path' implicitly has an 'any' type.
src/server/Master.ts(311,24): error TS7006: Parameter 'req' implicitly has an 'any' type.
src/server/Master.ts(311,29): error TS7006: Parameter 'res' implicitly has an 'any' type.
```
It seems that with strict mode enabled, ts-node requires the `@types/*` packages (which are devDependencies) to be present in the final image.

**Comment by scottanderson** [comment]
@aaa4xu how did you find those errors?

**Comment by aaa4xu** [comment]
I set `TS_NODE_LOG_ERROR=true` inside the container.
https://www.npmjs.com/package/ts-node#diagnostic-options

**Comment by scottanderson** [comment]
@aaa4xu is there a way we can get the errors to show up in the CI build or deploy job's build log?

For example, in https://github.com/openfrontio/OpenFrontIO/pull/1749 for [this run](https://github.com/openfrontio/OpenFrontIO/actions/runs/16819258843/job/47642917788?pr=1749).

Or in the main CI build step?

**Comment by aaa4xu** [comment]
The problem is that `ts-node` doesn’t have a build step. I’ll check later if we can feed the code into a regular `tsc` and use it as a linter.

The core issue is that when `ts-node` can’t find the typings, it tries to throw an exception, but due to a bug in its error formatting, it swallows it. Setting `TS_NODE_LOG_ERROR=true` makes it print the errors to stderr, but the side effect is that the errors no longer stop execution.

**Comment by scottanderson** [comment]
After doing a couple of experiments, I'm inclined to say that we should just remove `--omit=dev` from the docker build, since the docker image does actually run the node server.

**Comment by VariableVince** [comment]
Re-opened because PR 1749 was originally merged but that _main_ branch got renamed to _main-old_ and that is were the [commit ](https://github.com/openfrontio/OpenFrontIO/commit/0f713abd856a275b4f21aa902261473c2f7bd0c6) still resides, but was not committed to current _main_.

Which means pre-work was merged to enable strict mode. Then strict mode was enabled, but 'temporarily' disabled because of docker issues. And then re-enabled again but that commit isn't in current _main_ so it is still disabled.

The pre-work is still in main. Meaning there's less work than when starting from zero, but still a lot of work with all new code since then.

TypeScript v6 assumes strict to be true by default (https://devblogs.microsoft.com/typescript/announcing-typescript-6-0-rc/#simple-default-changes). We're on 5.8.3 now, 5.9 has been out for awhile and v6 RC was just released. And v6 is just an intermediate step to the faster native v7 which releases not too long from now and might be nice to work with for speed. One day we might need to move to strict:true after all.

**Comment by iiamlewis** [comment]
Will add to back end tasks for WS

**Comment by evanpelle** [comment]
Hi @scottanderson, this issue hasn't had activity in 5 days and doesn't yet have a milestone assigned.

If a maintainer doesn't milestone this issue (or you don't update it) within the next 5 days, it will be **automatically closed**.

If you believe this issue is important, consider:
- Adding more context, repro steps, or examples
- Discussing in our [Discord](https://discord.gg/K9zernJB5z)
- Requesting the `keep-open` label if it should be exempt from auto-close

— *Automated. See [CONTRIBUTING.md](https://github.com/openfrontio/OpenFrontIO/blob/main/CONTRIBUTING.md).*
